### ISSUE TITLE
Artifactory Gradle Task

### ISSUE THREAD

**Issue by AngelloMaggio** [jfrog/jfrog-azure-devops-extension#117]
Similar to our offerings for NPM, Docker, Maven, Go, etc, it would be ideal to have a Gradle Task as well to allow for the gathering of Build Info on Gradle builds. 
Since the JFrog CLI offers build commands for Gradle, and being that the Tools Task takes care of the Maven Extractor dependency, this would fit in really well with the existing tasks.

Currently the workaround is to create a POM from the Gradle build and use the Maven Task to collect dependency information.

**Comment by yahavi** [comment]
@AngelloMaggio,
the Artifactory Gradle task is included in the last release 1.9.0.
You can find the documentation [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-TriggeringGradleBuilds).
We'll appreciate your feedback for that.

**Comment by cubimon** [comment]
@yahavi does your artifactory gradle task work with java11/ubuntu-latest for you?

**Comment by PapaWhiskey65** [comment]
> @AngelloMaggio,
> the Artifactory Gradle task is included in the last release 1.9.0.
> You can find the documentation [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-TriggeringGradleBuilds).
> We'll appreciate your feedback for that.

the documentation is not really helpful...i've done jfrog cli with a build.gradle so i know how to do that...but is the build.gradle going to be the same for azure devops gradle deploy tasks? you really need to make quality documentation including things like the contents of a required file like build.gradle

**Comment by AndyGettingAn** [comment]
@PapaWhiskey65 I am struggling with the same issue and can't seem to find any helpful examples online. Have you managed to deploy an artifact using the Gradle task?

**Comment by PapaWhiskey65** [comment]
> @PapaWhiskey65 I am struggling with the same issue and can't seem to find any helpful examples online. Have you managed to deploy an artifact using the Gradle task?

i was able to upload via gradle, the integration with TFS/azure never seemed to work, and another engineer came up with how to upload via TFS

**Comment by AndyGettingAn** [comment]
I actually managed to deploy an artifact using the Artifactory Gradle Task. I had to set the artifactory plugin in my project build.gradle and use a system variable in the azure pipeline to access credentials which kinda makes the Gradle Task redundant and could have been done with a simple Gradle Task but still if someone is interested how I set up the task:

![Bildschirmfoto 2021-03-18 um 08 04 35](https://user-images.githubusercontent.com/24636447/111586436-1bd03580-87c1-11eb-92f1-573dbcea5188.png)

**Comment by mo-saeed** [comment]
@yahavi How can I define a snapshot repository besides a releases repository? and how to define more than one repos ?
